[profile.default]
src = "src"
out = "out"
libs = ["lib"]

# See more config options https://github.com/foundry-rs/foundry/tree/master/config

solc = "0.8.25"
# https://github.com/foundry-rs/foundry/issues/7607
unchecked_cheatcode_artifacts = true

# Try to make sure the optimizer doesn't touch the output in a way that can break
# source maps for debugging.
# via_ir = false
# optimizer = false
# optimizer_runs = 0
# optimizer_steps = 0

# These settings should be used for snapshots
optimizer = true
optimizer_runs = 1000000

bytecode_hash = "none"
cbor_metadata = false

fs_permissions = [
    { access = "read", path = "./out" },
    { access = "read", path = "lib/rain.interpreter/meta/RainterpreterExpressionDeployerNPE2.rain.meta" },
    { access = "write", path = "meta/AuthoringMeta.rain.meta" },
    { access = "read-write", path = "meta/UniswapWordsDescribedByMetaV1.rain.meta" },
]

remappings = [
    "rain.interpreter/=lib/rain.interpreter/src/",
    "rain.interpreter.interface/=lib/rain.interpreter/lib/rain.interpreter.interface/src/",
    "rain.metadata/=lib/rain.interpreter/lib/rain.metadata/src/",
    "rain.intorastring/=lib/rain.interpreter/lib/rain.intorastring/",
]

[fuzz]
runs = 2048

[profile.reference]

solc = "0.6.6"
src = "reference/src"
test = 'reference/test'
script = 'reference/script'
out = "out/reference/"
libs = ["reference/lib"]
remappings = [
    "v2-core/=reference/lib/v2-core/",
    "v2-periphery/=reference/lib/v2-periphery/",
    "@uniswap/v2-core/=reference/lib/v2-core/",
    "@uniswap/v2-periphery/=reference/lib/v2-periphery/"
]

[profile.quoter]

solc = "0.7.6"
src = "lib/view-quoter-v3/contracts"
test = "lib/view-quoter-v3/test"
script = "lib/view-quoter-v3/script"
out = "out/quoter/"
libs = ["lib/view-quoter-v3/lib"]
remappings = [
    "v3-periphery/=lib/view-quoter-v3/lib/v3-periphery/",
]